services:
  - type: web
    name: churn-prediction-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_app:app --host 0.0.0.0 --port $PORT
